// src/shared/strings.js
// All runtime user-visible English copy lives here (i18n-ready per ADR-0003).
// Static files (manifest.json, options.html) duplicate two values; the
// strings-source test keeps them locked to this module.
export const STRINGS = Object.freeze({
  extensionName: 'NightVeil',
  extensionDescription: 'Wrap the web in a gentle dark veil.',
  swStartedDebug: '[NightVeil] service worker started',
  contentActiveLog: '[NightVeil] content script active',
  optionsHeading: 'NightVeil Options',
  optionsNote: 'Changes save automatically.',
  optionsPreviewNote: 'Preview — extension storage is unavailable here, so controls are disabled.',
  optionsSaveError: '[NightVeil] failed to save settings:',
  resetButton: 'Reset to defaults',
  sectionThemesLabel: 'Themes',
  classicThemeLabel: 'Classic theme',
  overlayFamilyLabel: 'Overlay family — colors painted over the page',
  invertFamilyLabel: 'Invert family — filter inversion with media protection',
  siteThemesLabel: 'Site themes',
  siteThemesNote: 'Refinements applied on top of the classic theme for specific sites.',
  sectionOptionsLabel: 'Options',
  sectionUserCssLabel: 'User CSS',
  sectionUserCssNote: 'Write your own dark styles in a later milestone.',
  sectionEngineLabel: 'Adaptive engine',
  sectionEngineNote: 'Live color rewriting arrives in a later milestone.',
  sectionExclusionLabel: 'Exclusion',
  sectionInclusionLabel: 'Inclusion',
  sectionScheduleLabel: 'Schedule',
  sectionScheduleNote: 'Automatic daily on/off arrives in a later milestone.',
  stateTitleDark: 'NightVeil — Dark',
  stateTitleLight: 'NightVeil — Light',
  menuExcludeSite: 'Exclude this site from NightVeil',
  menuIncludeSite: 'Include this site in NightVeil',
  stateTitleSiteOn: 'NightVeil — Site included',
  stateTitleSiteOff: 'NightVeil — Site not included',
});
