// src/shared/strings.js
// All runtime user-visible English copy lives here (i18n-ready per ADR-0003).
// Static files (manifest.json, options.html) duplicate two values; the
// strings-source test keeps them locked to this module.
export const STRINGS = Object.freeze({
  extensionName: 'NightVeil',
  extensionDescription: 'Wrap the web in a gentle dark veil.',
  swStartedDebug: '[NightVeil] service worker started',
  contentActiveLog: '[NightVeil] content script active',
  optionsHeading: 'NightVeil Options',
  optionsNote: 'Changes save automatically.',
  optionsPreviewNote: 'Preview — extension storage is unavailable here, so controls are disabled.',
  optionsSaveError: '[NightVeil] failed to save settings:',
  resetButton: 'Reset to defaults',
  sectionThemesLabel: 'Themes',
  classicThemeLabel: 'Classic theme',
  overlayFamilyLabel: 'Overlay family — colors painted over the page',
  invertFamilyLabel: 'Invert family — filter inversion with media protection',
  siteThemesLabel: 'Site themes',
  siteThemesNote: 'Refinements applied on top of the classic theme for specific sites.',
  sectionOptionsLabel: 'Options',
  sectionUserCssLabel: 'User CSS',
  sectionUserCssNote: 'Write your own dark styles in a later milestone.',
  sectionEngineLabel: 'Adaptive engine',
  sectionEngineNote: 'Live color rewriting arrives in a later milestone.',
  sectionExclusionLabel: 'Exclusion',
  sectionInclusionLabel: 'Inclusion',
  sectionScheduleLabel: 'Schedule',
  sectionScheduleNote: 'Automatic daily on/off arrives in a later milestone.',
  behaviorLabel: 'Behavior',
  stateLightLabel: 'Light',
  stateDarkLabel: 'Dark',
  inclusionModeLabel: 'Inclusion mode — dark applies only to the inclusion list',
  inclusionModeNote: 'The exclusion list is ignored while this is on.',
  perSiteToggleLabel: 'Per-site toolbar toggle (inclusion mode only) — the toolbar button adds or removes the current site',
  rulesLabel: 'Exclusion rules',
  ruleMetaSchemeLabel: 'Skip pages that declare a dark color-scheme',
  ruleDarkBackgroundLabel: 'Skip pages whose background is already dark',
  ruleBrightnessLabel: 'Dark background threshold (0-255):',
  ruleHtmlAttributesLabel: 'HTML attributes (name or name=value, comma-separated):',
  ruleHtmlClassesLabel: 'HTML classes (comma-separated):',
  ruleCookiesLabel: 'Cookie names (comma-separated):',
  listEditHint: 'One hostname per line. "www." is ignored; an entry also covers its subdomains.',
  exclusionListLabel: 'Exclusion list',
  inclusionListLabel: 'Inclusion list',
  stateTitleDark: 'NightVeil — Dark',
  stateTitleLight: 'NightVeil — Light',
  menuExcludeSite: 'Exclude this site from NightVeil',
  menuIncludeSite: 'Include this site in NightVeil',
  stateTitleSiteOn: 'NightVeil — Site included',
  stateTitleSiteOff: 'NightVeil — Site not included',
});
