// src/shared/strings.js
// All runtime user-visible English copy lives here (i18n-ready per ADR-0003).
// Static files (manifest.json, options.html) duplicate two values; the
// strings-source test keeps them locked to this module.
export const STRINGS = Object.freeze({
  extensionName: 'NightVeil',
  extensionDescription: 'Wrap the web in a gentle dark veil.',
  swStartedDebug: '[NightVeil] service worker started',
  contentActiveLog: '[NightVeil] content script active',
  optionsHeading: 'NightVeil Options',
  optionsNote: 'Changes save automatically.',
  optionsPreviewNote: 'Preview — extension storage is unavailable here, so controls are disabled.',
  optionsSaveError: '[NightVeil] failed to save settings:',
  resetButton: 'Reset to defaults',
  sectionThemesLabel: 'Themes',
  classicThemeLabel: 'Classic theme',
  overlayFamilyLabel: 'Overlay family — colors painted over the page',
  invertFamilyLabel: 'Invert family — filter inversion with media protection',
  siteThemesLabel: 'Site themes',
  siteThemesNote: 'Refinements applied on top of the classic theme for specific sites.',
  sectionOptionsLabel: 'Options',
  sectionUserCssLabel: 'User CSS',
  sectionUserCssNote: 'Write your own dark styles in a later milestone.',
  sectionEngineLabel: 'Adaptive engine',
  sectionEngineNote: 'The adaptive engine rewrites the page CSS into dark colors live, while Dark is on. Its sub-options apply only while the engine is the selected theme.',
  engineSeatLabel: 'Use the adaptive engine (theme seat 41)',
  enginePolicyRespectLabel: 'Respect site themes — when a site theme matches, it is used and the engine stays off on that site',
  enginePolicyIgnoreLabel: 'Ignore site themes — the engine always runs and site themes never apply',
  enginePolicySkipCompatibleLabel: 'Skip only compatible sites — on the small compatibility list (Google, DuckDuckGo) the engine runs instead of the site theme',
  enginePolicyNote: 'Site themes normally take priority over the engine; this decides what happens when a site theme matches the current site.',
  engineColorsGroupLabel: 'Color rules — what gets darkened and how invalid colors fall back',
  engineBackgroundsGroupLabel: 'Background images and gradients',
  engineRulesGroupLabel: 'Priority, at-rules and context-aware colors',
  engineScopeGroupLabel: 'Inline styles, stylesheets, variables and change tracking',
  engineSitePolicyGroupLabel: 'Site theme policy',
  enginePerformanceGroupLabel: 'Performance and deep rules',
  engineDarkenTextLabel: 'Rewrite text color (color)',
  engineDarkenSvgFillLabel: 'Rewrite SVG fill color (fill)',
  engineDarkenSvgStrokeLabel: 'Rewrite SVG stroke color (stroke)',
  engineDarkenBorderLabel: 'Rewrite border and outline colors',
  engineDarkenBackgroundLabel: 'Rewrite background colors',
  engineDarkenBoxShadowLabel: 'Turn box-shadow into the shadow variable',
  engineDarkenTextShadowLabel: 'Turn text-shadow into the shadow variable',
  engineBorderNeedsWidthLabel: 'Only rewrite borders that declare an explicit width',
  engineBackgroundBlendLabel: 'Attach a blend-mode variable when a background color is rewritten',
  enginePreserveBackgroundPropsLabel: 'Keep background repeat and position when handling background images',
  engineIgnoreInitialPropsLabel: 'Ignore initial values when keeping background properties',
  engineFallbackEnabledLabel: 'Fall back to a color-mix when a color cannot be parsed',
  engineFallbackTransparencyLabel: 'Fallback color transparency adjustment (0-100%):',
  engineDarkenBackgroundImagesLabel: 'Darken background images with a veil or filter',
  engineRemoveGradientsLabel: 'Remove gradient background images entirely (none)',
  engineRemoveGradientColorsLabel: 'Replace gradient values with the fallback color',
  engineDarkenGradientsLabel: 'Prepend a darkening layer to gradients',
  engineDarkenGradientVariablesLabel: 'Also darken gradients found in custom properties',
  engineGradientShadeLabel: 'Darkening layer color:',
  engineHighPriorityLabel: 'Mark every engine rule !important',
  engineProcessMediaQueriesLabel: 'Rewrite rules inside @media',
  engineProcessKeyframesLabel: 'Rewrite @keyframes',
  engineProcessSupportsLabel: 'Rewrite @supports',
  engineContextAwareLabel: 'Context-aware coloring — off means the fallback color is always used',
  engineContextAwareTargetsTextLabel: 'Context-aware target: text',
  engineContextAwareTargetsBorderLabel: 'Context-aware target: border',
  engineContextAwareTargetsBackgroundLabel: 'Context-aware target: background',
  engineContextAwareTargetsSvgLabel: 'Context-aware target: SVG',
  engineAlphaRangeMinLabel: 'Alpha valid range minimum (0-100%):',
  engineAlphaRangeMaxLabel: 'Alpha valid range maximum (0-100%):',
  engineLuminanceRangeMinLabel: 'Relative luminance range minimum (0-100%):',
  engineLuminanceRangeMaxLabel: 'Relative luminance range maximum (0-100%):',
  enginePreserveAlphaLabel: 'Keep the original alpha when falling back',
  enginePreserveDarkColorsLabel: 'Keep original colors darker than the luminance minimum',
  engineNearWhiteAdjustEnabledLabel: 'Special handling for near-white colors',
  engineNearWhiteAdjustMinLabel: 'Near-white adjustment range minimum (0-100%):',
  engineNearWhiteAdjustMaxLabel: 'Near-white adjustment range maximum (0-100%):',
  engineNearWhiteAdjustPercentLabel: 'Near-white base darkening (0-100%):',
  engineProcessInlineStylesLabel: 'Rewrite inline style attributes',
  engineProcessShadowStylesLabel: 'Rewrite Shadow DOM and constructed stylesheets',
  engineMapCssVariablesLabel: 'Collect the page CSS variables for resolution',
  engineWatchClassChangesLabel: 'Rescan when element classes change',
  engineWatchNewElementsLabel: 'Keep processing elements added after load',
  enginePerformanceObserverLabel: 'Track long tasks with a PerformanceObserver',
  engineTuningPerformanceLabel: 'Tune for performance',
  engineTuningPageLoadLabel: 'Tune for page load (needs LongTaskTiming support)',
  engineDeepRulesLabel: 'Recurse into all nested rules',
  engineRecheckLabel: 'Re-check the page after load',
  engineRecheckDelayLabel: 'Re-check delay in milliseconds (0-10000):',
  engineTuningUnsupported: 'Page-load tuning needs PerformanceLongTaskTiming, which this browser does not provide. Performance tuning stays selected.',
  sectionExclusionLabel: 'Exclusion',
  sectionInclusionLabel: 'Inclusion',
  sectionScheduleLabel: 'Schedule',
  sectionScheduleNote: 'Automatic daily on/off arrives in a later milestone.',
  behaviorLabel: 'Behavior',
  stateLightLabel: 'Light',
  stateDarkLabel: 'Dark',
  inclusionModeLabel: 'Inclusion mode — dark applies only to the inclusion list',
  inclusionModeNote: 'The exclusion list is ignored while this is on.',
  perSiteToggleLabel: 'Per-site toolbar toggle (inclusion mode only) — the toolbar button adds or removes the current site',
  rulesLabel: 'Exclusion rules',
  ruleMetaSchemeLabel: 'Skip pages that declare a dark color-scheme',
  ruleDarkBackgroundLabel: 'Skip pages whose background is already dark',
  ruleBrightnessLabel: 'Dark background threshold (0-255):',
  ruleHtmlAttributesLabel: 'HTML attributes (name or name=value, comma-separated):',
  ruleHtmlClassesLabel: 'HTML classes (comma-separated):',
  ruleCookiesLabel: 'Cookie names (comma-separated):',
  listEditHint: 'One hostname per line. "www." is ignored; an entry also covers its subdomains.',
  exclusionListLabel: 'Exclusion list',
  inclusionListLabel: 'Inclusion list',
  stateTitleDark: 'NightVeil — Dark',
  stateTitleLight: 'NightVeil — Light',
  menuExcludeSite: 'Exclude this site from NightVeil',
  menuIncludeSite: 'Include this site in NightVeil',
  stateTitleSiteOn: 'NightVeil — Site included',
  stateTitleSiteOff: 'NightVeil — Site not included',
});
